title: desvert's Blog
description: Hacking notes, walkthroughs, and tech stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://desvert.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-theme-clean-blog
  - jekyll-remote-theme

remote_theme: pages-themes/slate@v0.2.0
google_analytics: 
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
