title: desvert's blog
description: Hacking notes, walkthroughs, and tech stuff.
url: "https://desvert.github.io" # change if using a custom domain
baseurl: "" # keep empty for user site like desvert.github.io

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
